// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSXNzIPmtSQ1hniuy_lnQoiCp56t4Sz1E',
    appId: '1:879955760620:android:d97f514c360861feaa5cc9',
    messagingSenderId: '879955760620',
    projectId: 'digitalgrub-f40e4',
    databaseURL: 'https://digitalgrub-f40e4.firebaseio.com',
    storageBucket: 'digitalgrub-f40e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwoMM0y9yeenavsrMee3Y1R3eRu96rPo',
    appId: '1:879955760620:ios:98c0647cf62f77b6aa5cc9',
    messagingSenderId: '879955760620',
    projectId: 'digitalgrub-f40e4',
    databaseURL: 'https://digitalgrub-f40e4.firebaseio.com',
    storageBucket: 'digitalgrub-f40e4.firebasestorage.app',
    iosBundleId: 'com.digitalgrub.scrapTyreBusinessManager',
  );
}
